development:
  adapter: postgresql
  database: numerology_development
  pool: 5
  host: localhost
  username: lisapaulsavoie
  password: ''

test:
  adapter: postgresql
  database: numerology_test
  pool: 5
  host: localhost
  username: lisapaulsavoie
  password: ''
